development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://h:p483a5a5d25959bb9a90c273342aaa5b95a04417974415353bc36e9c37df2d0a2@ec2-34-228-0-121.compute-1.amazonaws.com:29199
  channel_prefix: message-me_production
